name: "Review Docs on Pull Request"
on:
  - pull_request

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v1
      - name: Auto insert Sphinx warnings in Pull Request Body
        uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "docs/"
          pre-build-command: "pip install pipenv && pipenv install && pipenv shell && pip install sphinx-rtd-theme"
          build-command: "make html"
      - name: Auto Assign Reviewers
        uses: kentaro-m/auto-assign-action@v1.1.2
        with:
          configuration-path: ".github/config/auto_assign.yml"
